### ISSUE TITLE
make issue related with __m256i functions 

### ISSUE THREAD

**Issue by burakkoca** [RapidsAtHKUST/SubgraphMatching#1]
First, thanks for the comprehensive study but I get several errors during make operation such as " error: inlining failed in call to always_inline ‘__m256i _mm256_permutevar8x32_epi32(__m256i, __m256i)’: target specific option mismatch". It's probably a compatibility problem with compiler or CPU. My current OS is Ubuntu 18.4 and the CPU is intel i7 970.

**Comment by shixuansun** [comment]
Hi, thanks for your question. According to the document from intel (https://ark.intel.com/content/www/us/en/ark/products/47933/intel-core-i7-970-processor-12m-cache-3-20-ghz-4-80-gt-s-intel-qpi.html?ui=BIG), your CPU cannot support AVX2. Therefore, you should disable the AVX2 in the source code by following README.md.

**Comment by shixuansun** [comment]
> First, thanks for the comprehensive study but I get several errors during make operation such as " error: inlining failed in call to always_inline ‘__m256i _mm256_permutevar8x32_epi32(__m256i, __m256i)’: target specific option mismatch". It's probably a compatibility problem with compiler or CPU. My current OS is Ubuntu 18.4 and the CPU is intel i7 970.

Hi, thanks for your question. According to the document from intel (https://ark.intel.com/content/www/us/en/ark/products/47933/intel-core-i7-970-processor-12m-cache-3-20-ghz-4-80-gt-s-intel-qpi.html?ui=BIG), your CPU cannot support AVX2. Therefore, you should disable the AVX2 in the source code by following README.md.
