### ISSUE TITLE
License for Rust port

### ISSUE THREAD

**Issue by s1ck** [RapidsAtHKUST/SubgraphMatching#2]
Hello! Thanks for the great comparison and providing the source code to study your work. I'd like to port the implementation to Rust (https://github.com/s1ck/subgraph-matching) and maybe adapt it to directed graphs. I was wondering which license to use. I usually opt for MIT or Apache 2.0. Please let me know what you think.

**Comment by shixuansun** [comment]
Hi, thanks for your interest in our project. I prefer the MIT license.

Thanks.

**Comment by s1ck** [comment]
Thanks for the fast reply! MIT it is :+1:
